#!/bin/bash

# Start + detach servers
cd ~/sumdog_web
dc up -d

# Start working tmux session
tmux new-session -d -e RAILS_ENV=development
tmux split-window -v yarn build --watch
tmux split-window -h yarn test --watchAll

# Create a new pane for Rails console on the top layer
tmux select-pane -t 0
tmux split-window -h docker compose exec rails bundle exec rails console

# Increase width of test pane
tmux select-pane -t 3
tmux resize-pane -x 80%

# Set focus on the first pane (working pane) + make it wider
tmux select-pane -t 0
tmux resize-pane -x 80%

tmux -2 attach-session -d
